# Generated by Django 2.0.1 on 2018-03-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCommentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15, null=True)),
                ('commentaire', models.CharField(max_length=500, null=True)),
                ('ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ContactCommentaire')),
            ],
        ),
    ]
